# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f9:28:a9:a7:87:d6:b2:7e:db:85:31:cb:64:00:ab:d3"

      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts

      - deploy:
          name: Start master deploy
          command: |
            if ["${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/home/${USER_NAME}/htdocs/public_html/
            fi
            